services:
  - type: web
    name: fbox-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot_handler.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: FBOX_SSID
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: DROPBOX_PATH
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
